src/Entity/Event.php
<?php

namespace App\Entity; 

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $nom_event = null;

    #[ORM\Column(length: 255)]
    private ?string $discription_event = null;

    #[ORM\Column(length: 255)]
    private ?string $image_event = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_debut_event = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin_event = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse_event = null;

    #[ORM\OneToMany(mappedBy: 'eventID', targetEntity: EventTicket::class)]
    private Collection $eventTick;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $reserve = null;

    public function __construct()
    {
        $this->eventTick = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEvent(): ?string
    {
        return $this->nom_event;
    }

    public function setNomEvent(string $nom_event): self
    {
        $this->nom_event = $nom_event;

        return $this;
    }

    public function getDiscriptionEvent(): ?string
    {
        return $this->discription_event;
    }

    public function setDiscriptionEvent(string $discription_event): self
    {
        $this->discription_event = $discription_event;

        return $this;
    }

    public function getImageEvent(): ?string
    {
        return $this->image_event;
    }

    public function setImageEvent(string $image_event): self
    {
        $this->image_event = $image_event;

        return $this;
    }

    public function getDateDebutEvent(): ?\DateTimeInterface
    {
        return $this->date_debut_event;
    }

    public function setDateDebutEvent(\DateTimeInterface $date_debut_event): self
    {
        $this->date_debut_event = $date_debut_event;

        return $this;
    }

    public function getDateFinEvent(): ?\DateTimeInterface
    {
        return $this->date_fin_event;
    }

    public function setDateFinEvent(\DateTimeInterface $date_fin_event): self
    {
        $this->date_fin_event = $date_fin_event;

        return $this;
    }

    public function getAdresseEvent(): ?string
    {
        return $this->adresse_event;
    }

    public function setAdresseEvent(string $adresse_event): self
    {
        $this->adresse_event = $adresse_event;

        return $this;
    }

    /**
     * @return Collection<int, EventTicket>
     */
    public function getEventTick(): Collection
    {
        return $this->eventTick;
    }

    public function addEventTick(EventTicket $eventTick): self
    {
        if (!$this->eventTick->contains($eventTick)) {
            $this->eventTick->add($eventTick);
            $eventTick->setEventID($this);
        }

        return $this;
    }

    public function removeEventTick(EventTicket $eventTick): self
    {
        if ($this->eventTick->removeElement($eventTick)) {
            // set the owning side to null (unless already changed)
            if ($eventTick->getEventID() === $this) {
                $eventTick->setEventID(null);
            }
        }

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getReserve(): ?string
    {
        return $this->reserve;
    }

    public function setReserve(?string $reserve): self
    {
        $this->reserve = $reserve;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_event')
            ->add('discription_event')
            ->add('image_event')
            ->add('date_debut_event')
            ->add('date_fin_event')
            ->add('adresse_event')
            ->add('status',ChoiceType::class , [
                'choices'=>[
                    'Confirmé'=>'Confirmé',
                    'En attente'=>'En attente',
                    'Annulé'=>'Annulé' ],
                'attr' => ['class' => 'form-select'],
                'label_attr' => ['class' => 'form-label'],
            ])
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/event')]
class EventController extends AbstractController
{
    #[Route('/', name: 'app_event_index', methods: ['GET'])]
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_event_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EventRepository $eventRepository): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $eventRepository->save($event, true);

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_show', methods: ['GET'])]
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_event_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Event $event, EventRepository $eventRepository): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $eventRepository->save($event, true);

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_delete', methods: ['POST'])]
    public function delete(Request $request, Event $event, EventRepository $eventRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->request->get('_token'))) {
            $eventRepository->remove($event, true);
        }

        return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn btn-primary py-2 px-4 mt-4">Supprimer</button>
</form>

templates/event/_form.html.twig
<div class="container">
{{ form_start(form,{'attr':{'novalidate':'novalidate'}}) }}

<div class="from-group"
     {{ form_label(form.nom_event,"Nom Event") }}
     {{ form_widget(form.nom_event,{'attr':{'class':'from-control'}}) }}
     {% if form_errors(form.nom_event) is not empty %}
     <div class="alert alert-danger">
     {{ form_errors(form.nom_event) }}
</div>
{% endif %}
</div>

<div class="from-group"
     {{ form_label(form.discription_event,"Discription event") }}
     {{ form_widget(form.discription_event,{'attr':{'class':'from-control'}}) }}
     {% if form_errors(form.discription_event) is not empty %}
     <div class="alert alert-danger">
     {{ form_errors(form.discription_event) }}
 </div>
 {% endif %}
 </div>


 <div class="from-group"
     {{ form_label(form.image_event,"Image Event") }}
     {{ form_widget(form.image_event,{'attr':{'class':'from-control'}}) }}
     {% if form_errors(form.image_event	) is not empty %}
     <div class="alert alert-danger">
     {{ form_errors(form.image_event) }}
 </div>  
{% endif %}
</div>


 <div class="from-group"
     {{ form_label(form.date_debut_event,"Date debut") }}
     {{ form_widget(form.date_debut_event,{'attr':{'class':'from-control'}}) }}
     {% if form_errors(form.date_debut_event) is not empty %}
     <div class="alert alert-danger">
     {{ form_errors(form.date_debut_event) }}
 </div>  
{% endif %}
</div>

 <div class="from-group"
     {{ form_label(form.date_fin_event,"Date fin") }}
     {{ form_widget(form.date_fin_event,{'attr':{'class':'from-control'}}) }}
     {% if form_errors(form.date_fin_event) is not empty %}
     <div class="alert alert-danger">
     {{ form_errors(form.date_fin_event) }}
 </div>  
{% endif %}
 </div> 

 <div class="from-group"
     {{ form_label(form.adresse_event,"Adresse evenement") }}
     {{ form_widget(form.adresse_event,{'attr':{'class':'from-control'}}) }}
     {% if form_errors(form.adresse_event) is not empty %}
     <div class="alert alert-danger">
     {{ form_errors(form.adresse_event) }}
 </div>  
{% endif %}
 </div>
 <div class="from-group"
     {{ form_label(form.status,"Statut") }}
     {{ form_widget(form.status,{'attr':{'class':'from-control'}}) }}
     {% if form_errors(form.status) is not empty %}
     <div class="alert alert-danger">
     {{ form_errors(form.status) }}
 </div>  
{% endif %}
 </div>    
    <button class="btn btn-primary py-2 px-4 mt-4">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}
</div>

templates/event/edit.html.twig
{% extends 'base_back_event.html.twig' %}

{% block title %}Modifier Évenement{% endblock %}

{% block body %}
    
            <div class="container-fluid pt-4 px-4">
                <div class="bg-light rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            <h1>Modifier un Évenement</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('app_event_index') }}"class="btn btn-primary py-2 px-4 mt-4">Liste des Évenements</a>

    {{ include('event/_delete_form.html.twig') }}

                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                           
                        </div>
                    </div>
                </div>
            </div>
{% endblock %}

templates/event/index.html.twig
{% extends 'base_back_event.html.twig' %}

{% block title %}Ajoute Event {% endblock %}

{% block body %}
    <h1>Event index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_event</th>
                <th>Discription_event</th>
                <th>Image_event</th>
                <th>Date_debut_event</th>
                <th>Date_fin_event</th>
                <th>Adresse_event</th>
                <th>Status</th>
                <th>Reserve</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for event in events %}
            <tr>
                <td>{{ event.id }}</td>
                <td>{{ event.nomEvent }}</td>
                <td>{{ event.discriptionEvent }}</td>
                <td>{{ event.imageEvent }}</td>
                <td>{{ event.dateDebutEvent ? event.dateDebutEvent|date('Y-m-d') : '' }}</td>
                <td>{{ event.dateFinEvent ? event.dateFinEvent|date('Y-m-d') : '' }}</td>
                <td>{{ event.adresseEvent }}</td>
                <td>{{ event.status }}</td>
                <td>{{ event.reserve }}</td>
                <td>
                    <a href="{{ path('app_event_show', {'id': event.id}) }}">show</a>
                    <a href="{{ path('app_event_edit', {'id': event.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_event_new') }}">Create new</a>
{% endblock %}

templates/event/new.html.twig
{% extends 'base_back_event.html.twig' %}

{% block title %}Ajouter Évenements{% endblock %}

{% block body %}

<div class="container-fluid pt-4 px-4">
                <div class="bg-light rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            <h1>Ajouter un Évenement</h1>
                            
                             
                            {{ include('event/_form.html.twig') }} 

                            <a href="{{ path('app_event_index') }}"class="btn btn-primary py-2 px-4 mt-4">Afficher les Évenements</a>
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                        
                           
                        </div>
                    </div>
                </div>
</div>

   
{% endblock %}

templates/event/show.html.twig
{% extends 'base_back_event.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <h1>Event</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ event.id }}</td>
            </tr>
            <tr>
                <th>Nom_event</th>
                <td>{{ event.nomEvent }}</td>
            </tr>
            <tr>
                <th>Discription_event</th>
                <td>{{ event.discriptionEvent }}</td>
            </tr>
            <tr>
                <th>Image_event</th>
                <td>{{ event.imageEvent }}</td>
            </tr>
            <tr>
                <th>Date_debut_event</th>
                <td>{{ event.dateDebutEvent ? event.dateDebutEvent|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin_event</th>
                <td>{{ event.dateFinEvent ? event.dateFinEvent|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Adresse_event</th>
                <td>{{ event.adresseEvent }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ event.status }}</td>
            </tr>
            <tr>
                <th>Reserve</th>
                <td>{{ event.reserve }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_event_index') }}">back to list</a>

    <a href="{{ path('app_event_edit', {'id': event.id}) }}">edit</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}