src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_produit = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $quantite_produit = null;

    #[ORM\Column]
    private ?float $prix = null;

    #[ORM\Column(length: 255)]
    private ?string $image_produit = null;

    #[ORM\Column(length: 255)]
    private ?string $marque = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categorie $categorie_produit = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProduit(): ?string
    {
        return $this->nom_produit;
    }

    public function setNomProduit(string $nom_produit): self
    {
        $this->nom_produit = $nom_produit;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getQuantiteProduit(): ?int
    {
        return $this->quantite_produit;
    }

    public function setQuantiteProduit(int $quantite_produit): self
    {
        $this->quantite_produit = $quantite_produit;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getImageProduit(): ?string
    {
        return $this->image_produit;
    }

    public function setImageProduit(string $image_produit): self
    {
        $this->image_produit = $image_produit;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getCategorieProduit(): ?Categorie
    {
        return $this->categorie_produit;
    }

    public function setCategorieProduit(?Categorie $categorie_produit): self
    {
        $this->categorie_produit = $categorie_produit;

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Range;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Validator\Constraints\Length;



class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('description', TextType::class, [
                'label' => 'Nom du produit',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Le description du produit ne peut pas être vide',
                    ]),
                ],
            ])
            ->add('prix', NumberType::class, [
                'label' => 'Prix',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Price cannot be blank',
                    ]),
                    new Range([
                        'min' => 0.0,
                        'max' => 100000000.0,
                        'notInRangeMessage' => 'Price must be between {{ min }} and {{ max }}',
                    ]),
                ],
            ])
            ->add('categorie_produit')
            ->add('image_produit', FileType::class, [
                'label' => 'Image Produit',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new \Symfony\Component\Validator\Constraints\Image([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid JPG/PNG document',
                    ])
                ],
                 ])
            ->add('nom_produit', TextType::class, [
                'label' => 'Nom du produit',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Le nom du produit ne peut pas être vide',
                    ]),
                    new Length([
                        'min' => 3,
                        'max' => 40,
                        'minMessage' => 'Le nom du produit doit comporter au moins {{ limit }} caractères',
                        'maxMessage' => 'Le nom du produit ne doit pas comporter plus de {{ limit }} caractères',
                    ]),
                ],
            ])
            ->add('marque', TextType::class, [
                'label' => 'Marque',
                'constraints' => [
                    new NotBlank([
                        'message' => 'La marque  du produit ne peut pas être vide',
                    ]),
                    new Length([
                        'min' => 4,
                        'max' => 20,
                        'minMessage' => 'La marque du produit doit comporter au moins {{ limit }} caractères',
                        'maxMessage' => 'La marquedu produit ne doit pas comporter plus de {{ limit }} caractères',
                    ]),
                ],
            ])
            ->add('quantite_produit', IntegerType::class, [
                'label' => 'Age',
                'constraints' => [
                    new NotBlank([
                        'message' => 'the quantity cannot be blank',
                    ]),
                    new Range([
                        'min' => 1,
                        'max' => 1000,
                        'notInRangeMessage' => 'the quantity must be between {{ min }} and {{ max }}',
                    ]),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;




#[Route('/produit')]
class ProduitController extends AbstractController
{
    #[Route('/', name: 'app_produit_index', methods: ['GET'])]
    public function index(ProduitRepository $produitRepository,Request $request, PaginatorInterface $paginator): Response
    {
        $produit=$produitRepository->findAll();
        $pagination = $paginator->paginate(
            $produit,
            $request->query->getInt('page', 1), // Current page number
            5 // Number of items per page
        );

        return $this->render('produit/index.html.twig' , [
            'produits' => $produit,
            'pagination' => $pagination,

        ]);
    }


    #[Route('/new', name: 'app_produit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ProduitRepository $produitRepository): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);






        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('image_produit')->getData();
            $Filename = md5(uniqid()).'.'.$imageFile->guessExtension();
            try {
                $imageFile->move(
                    $this->getParameter('images_directory'),
                    $Filename
                );
            } catch (FileException $e) {

            }

            $produit->setImageProduit($Filename);

            $produitRepository->save($produit, true);

            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_show', methods: ['GET'])]
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_produit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produit $produit, ProduitRepository $produitRepository): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('image_produit')->getData();
            $Filename = md5(uniqid()).'.'.$imageFile->guessExtension();
            try {
                $imageFile->move(
                    $this->getParameter('images_directory'),
                    $Filename
                );
            } catch (FileException $e) {

            }

            $produit->setImageProduit($Filename);

            $produitRepository->save($produit, true);

            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_delete', methods: ['POST'])]
    public function delete(Request $request, Produit $produit, ProduitRepository $produitRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $produitRepository->remove($produit, true);
        }

        return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
    }

}

templates/produit/_delete_form.html.twig
<form  method="post" action="{{ path('app_produit_delete', {'id': produit.id}) }}"
        >
    <input type="hidden" name="_token"  value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn btn-sm btn-primary" >Delete</button>
</form>

templates/produit/_form.html.twig
{{ form_start(form ,{'attr':{'novalidate':'novalidate'}})}}

<div class="col-sm-12 col-xl-6">
    <div class="bg-light rounded h-100 p-4">
        <form>
            <div class="row mb-3">
                {{form_label(form.nom_produit,'Nom Produit : ',{'attr':{'class':'form-label'}})}}
                {{form_widget(form.nom_produit,{'attr':{'class':'form-control', 'placeholder': 'Enter your product name'}})}}
                {{form_errors(form.nom_produit)}}

            </div>
            <div class="row mb-3">
                {{form_label(form.categorie_produit,'Catégorie : ',{'attr':{'class':'form-label'}})}}
                {{form_widget(form.categorie_produit,{'attr':{'class':'form-select'}})}}
                {{form_errors(form.categorie_produit)}}

            </div>
            <div class="row mb-3">
                {{form_label(form.description,'description : ',{'attr':{'class':'form-label'}})}}
                {{form_widget(form.description,{'attr':{'class':'form-control', 'placeholder': 'Enter your produit description'}})}}
                {{form_errors(form.description)}}
            </div>
            <div class="row mb-3">
                {{form_label(form.quantite_produit,'Quantite Produit : ',{'attr':{'class':'form-label'}})}}
                {{form_widget(form.quantite_produit,{'attr':{'class':'form-control', 'placeholder': 'Enter your product quantity enter  1 and 100'}})}}
                {{form_errors(form.quantite_produit)}}

            </div>
            <div class="row mb-3">
                {{form_label(form.prix,'Prix : ',{'attr': {'class': 'form-label'}})}}
                {{form_widget(form.prix,{'attr':{'class':'form-control', 'placeholder': 'Enter your price in dinars'}})}}
                {{form_errors(form.prix)}}
              </div>
            <div>
                {{form_label(form.image_produit,'Image : ',{'attr':{'class':'form-label'}})}}
                {{form_widget(form.image_produit,{'attr':{'class':'form-control' }})}}
                {{form_errors(form.image_produit)}}

            </div>
            <div>
                {{form_label(form.marque,'marque : ',{'attr':{'class':'form-label'}})}}
                {{form_widget(form.marque,{'attr':{'class':'form-control', 'placeholder': 'Enter your product brand'}})}}
                {{form_errors(form.marque)}}

            </div>


        </form>
    </div>
    <button class="btn btn-sm btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/produit/custoom_pagination.html.twig
{% if pageCount > 1 %}
    <ul class="pagination justify-content-center">
        {% if current == 1 %}
            <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="{{ path(route, query|merge({(pageParameterName): 1})) }}">&laquo;</a></li>
        {% endif %}

        {% for page in pagesInRange %}
            {% if page != current %}
                <li class="page-item"><a class="page-link" href="{{ path(route, query|merge({(pageParameterName): page})) }}">{{ page }}</a></li>
            {% else %}
                <li class="page-item active"><span class="page-link">{{ page }}</span></li>
            {% endif %}
        {% endfor %}

        {% if current == pageCount %}
            <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="{{ path(route, query|merge({(pageParameterName): pageCount})) }}">&raquo;</a></li>
        {% endif %}
    </ul>
{% endif %}

templates/produit/edit.html.twig
{% extends 'produitback.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    <h1>Edit Produit</h1>

    {{ include('produit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_produit_index') }}"class="btn btn-sm btn-primary">back to list</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/index.html.twig
{% extends 'produitback.html.twig' %}

{% block title %}Equipements paramedicaux {% endblock %}

{% block body %}

    <h1>Equipements paramedicaux</h1>
<div class="container-fluid pt-12 px-12">
    <div class="row g-12">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-light rounded h-150 p-12">
                <h6 class="mb-8">Tables des produits</h6>
                <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Nom_produit</th>
            <th>Description</th>
            <th>Quantite_produit</th>
            <th>Prix</th>
            <th>Marque</th>
            <th>Categorie</th>
            <th>Images</th>
            <th>actions</th>
        </tr>

        </thead>
        <tbody>

        {% for produit in pagination %}
            <tr>
                <td>{{ produit.id }}</td>
                <td>{{ produit.nomProduit }}</td>
                <td>{{ produit.description }}</td>
                <td>{{ produit.quantiteProduit }}</td>
                <td>{{ produit.prix }}</td>
                <td>{{ produit.marque }}</td>
                <td>{{ produit.categorieProduit }}</td>


                <td><img src="{{ asset('assets/uploads/' ~ produit.imageProduit) }}" width="120" height="120"></td>



                <td>  {{ include('produit/_delete_form.html.twig') }} </td>
                <td><a  href="{{ path('app_produit_edit', {'id': produit.id}) }}" class="btn btn-sm btn-primary" href="">EDIT </a></td>


            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
                </table>
                {{ knp_pagination_render(pagination, 'produit/custoom_pagination.html.twig') }}

            </div>
        </div>

        <h1><a  href="{{ path('app_produit_new') }}" class="btn btn-sm btn-primary" href="">Ajouter </a></h1>




{% endblock %}

templates/produit/new.html.twig
{% extends 'produitback.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
    <h1>ajouter un nouveau Produit</h1>

    {{ include('produit/_form.html.twig') }}

    <a href="{{ path('app_produit_index') }}" class="btn btn-sm btn-primary">back to list</a>
{% endblock %}

templates/produit/show.html.twig
{% extends 'produitback.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Nom_produit</th>
                <td>{{ produit.nomProduit }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ produit.description }}</td>
            </tr>
            <tr>
                <th>Quantite_produit</th>
                <td>{{ produit.quantiteProduit }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ produit.prix }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ produit.etat ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ produit.imageProduit}}</td>
            </tr>

        </tbody>
    </table>

    <a href="{{ path('app_produit_index') }}" class="btn btn-sm btn-primary">back to list</a>

    <a href="{{ path('app_produit_edit', {'id': produit.id}) }}">edit</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}