src/Entity/Categorie.php
<?php

namespace App\Entity; 

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
class Categorie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_categorie = null;

    #[ORM\OneToMany(mappedBy: 'categorie_produit', targetEntity: Produit::class)]
    private Collection $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCategorie(): ?string
    {
        return $this->nom_categorie;
    }

    public function setNomCategorie(string $nom_categorie): self
    {
        $this->nom_categorie = $nom_categorie;

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->setCategorieProduit($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getCategorieProduit() === $this) {
                $produit->setCategorieProduit(null);
            }
        }

        return $this;
    }
}

src/Form/CategorieType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class CategorieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_categorie', TextType::class, [
                'label' => 'Categorie',
                'constraints' => [
                    new NotBlank([
                        'message' => 'La Categorie ne peut pas être vide',
                    ]),
                    new Length([
                        'min' => 4,
                        'max' => 20,
                        'minMessage' => 'La Categorie doit comporter au moins {{ limit }} caractères',
                        'maxMessage' => 'La Categorie ne doit pas comporter plus de {{ limit }} caractères',
                    ]),
                ],
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Categorie::class,
        ]);
    }
}

src/Controller/CategorieController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\CategorieType;
use App\Repository\CategorieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/categorie')]
class CategorieController extends AbstractController
{
    #[Route('/', name: 'app_categorie_index', methods: ['GET'])]
    public function index(CategorieRepository $categorieRepository): Response
    {
        return $this->render('categorie/index.html.twig', [
            'categories' => $categorieRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_categorie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CategorieRepository $categorieRepository): Response
    {
        $categorie = new Categorie();
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $categorieRepository->save($categorie, true);

            return $this->redirectToRoute('app_categorie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('categorie/new.html.twig', [
            'categorie' => $categorie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_categorie_show', methods: ['GET'])]
    public function show(Categorie $categorie): Response
    {
        return $this->render('categorie/show.html.twig', [
            'categorie' => $categorie,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_categorie_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Categorie $categorie, CategorieRepository $categorieRepository): Response
    {
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $categorieRepository->save($categorie, true);

            return $this->redirectToRoute('app_categorie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('categorie/edit.html.twig', [
            'categorie' => $categorie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_categorie_delete', methods: ['POST'])]
    public function delete(Request $request, Categorie $categorie, CategorieRepository $categorieRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$categorie->getId(), $request->request->get('_token'))) {
            $categorieRepository->remove($categorie, true);
        }

        return $this->redirectToRoute('app_categorie_index', [], Response::HTTP_SEE_OTHER);
    }



}

templates/categorie/_delete_form.html.twig
<form method="post" action="{{ path('app_categorie_delete', {'id': categorie.id}) }}" >
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ categorie.id) }}">
    <button class="btn btn-sm btn-primary" >Delete</button>
</form>

templates/categorie/_form.html.twig
{{ form_start(form ,{'attr':{'novalidate':'novalidate'}})}}

<div class="col-sm-12 col-xl-6">
    <div class="bg-light rounded h-100 p-4">
        <form>
            <div class="row mb-3">
                {{form_label(form.nom_categorie,'Nom Categorie : ',{'attr':{'class':'form-label'}})}}
                {{form_widget(form.nom_categorie,{'attr':{'class':'form-control'}})}}
                {{form_errors(form.nom_categorie)}}

            </div>

        </form>
    </div>
    <button class="btn btn-sm btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/categorie/edit.html.twig
{% extends 'produitback.html.twig' %}

{% block title %}Edit Categorie{% endblock %}

{% block body %}
    <h1>Edit Categorie</h1>

    {{ include('categorie/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_categorie_index') }}">back to list</a>

    {{ include('categorie/_delete_form.html.twig') }}
{% endblock %}

templates/categorie/index.html.twig
{% extends 'produitback.html.twig' %}

{% block title %}Categories{% endblock %}

{% block body %}
    <h1>Categories</h1>
<div class="container-fluid pt-8 px-8">
    <div class="row g-8">
        <div class="col-sm-12 col-xl-8">
            <div class="bg-light rounded h-150 p-8">
                <h6 class="mb-8">Tables des catégories</h6>
                <table class="table">
                    <thead>
            <tr>
                <th>Id</th>
                <th>Nom_categorie</th>
                <th>produits</th>


                <th>actions</th>
            </tr>
        </thead>
        <tbody>

        {% for categorie in categories %}
            <tr>
                <td>{{ categorie.id }}</td>
                <td>{{ categorie.nomCategorie }}</td>
                <td>{{ categorie.getNbProduits() ~ ' ' ~ 'produits'}}</td>
                <td>    {{ include('categorie/_delete_form.html.twig') }}</td>

                <td><a  href="{{ path('app_categorie_show', {'id': categorie.id}) }}" class="btn btn-sm btn-primary" href="">Show</a></td>
                <td><a  href="{{ path('app_categorie_edit', {'id': categorie.id}) }}" class="btn btn-sm btn-primary" href="">EDIT </a></td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
                </table>
            </div>
        </div>

                <h1><a  href="{{ path('app_categorie_new') }}" class="btn btn-sm btn-primary" href="">Ajouter </a></h1>


                {% endblock %}

templates/categorie/new.html.twig
{% extends 'produitback.html.twig' %}

{% block title %}New Categorie{% endblock %}

{% block body %}
    <h1>Create new Categorie</h1>

    {{ include('categorie/_form.html.twig') }}

    <a href="{{ path('app_categorie_index') }}" class="btn btn-sm btn-primary" >back to list</a>
{% endblock %}

templates/categorie/show.html.twig
{% extends 'produitback.html.twig' %}

{% block title %}Categorie{% endblock %}

{% block body %}
    <h1>Categorie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ categorie.id }}</td>

            </tr>
            <tr>
                <th>Nom_categorie</th>
                <td>{{ categorie.nomCategorie }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_categorie_index') }}" class="btn btn-sm btn-primary" >back to list</a>

    <a href="{{ path('app_categorie_edit', {'id': categorie.id}) }}"> class="btn btn-sm btn-primary" edit</a>

    {{ include('categorie/_delete_form.html.twig') }}
{% endblock %}